blueprint:
  name: Alerte qualite d'eau - Piscinexa
  description: Envoie une notification si l'etat global de la piscine passe a "alerte"
  domain: automation
  input:
    piscine_global_sensor:
      name: Capteur etat global piscine
      selector:
        entity:
          domain: sensor
    notification_target:
      name: Cible de la notification
      selector:
        target: {}

trigger:
  - platform: state
    entity_id: !input piscine_global_sensor
    to: "alerte"

condition: []

action:
  - service: notify.notify
    target: !input notification_target
    data:
      message: >
        Alerte qualite d'eau : l'etat global de votre piscine est passe en alerte.
        Verifiez le pH, le taux de chlore et la temperature.

mode: single
