test_calcul:
  description: services.test_calcul.description
  fields:
    name:
      description: services.test_calcul.fields.name.description
      example: "papa"
reset_valeurs:
  description: services.reset_valeurs.description
  fields:
    name:
      description: services.reset_valeurs.fields.name.description
      example: "papa"
apply_treatment:
  description: services.apply_treatment.description
  fields:
    name:
      description: services.apply_treatment.fields.name.description
      example: "papa"
    treatment_type:
      description: services.apply_treatment.fields.treatment_type.description
      example: "Chlore"
    treatment_form:
      description: services.apply_treatment.fields.treatment_form.description
      example: "Liquide"
    quantity:
      description: services.apply_treatment.fields.quantity.description
      example: 5.0
