test_calcul:
  description: Teste le calcul pour une piscine spécifique
  fields:
    name:
      description: Nom de la piscine
      example: "papa"
reset_valeurs:
  description: Réinitialise les valeurs pour une piscine spécifique
  fields:
    name:
      description: Nom de la piscine
      example: "papa"
